#### Preamble ####
# Purpose: Simulates dataset of "Wheels of Misfortune: Exploring Auto Theft Trends in Ottawa"
# Author: Catherine Punnoose
# Date: 24 April 2024
# Contact: catherine.punnoose@mail.utoronto.ca
# License: MIT


#### Workspace setup ####
library(tidyverse)
library(janitor)
library(ggplot2)

#### Simulate data ####
# Code Generated by Chat GPT 3.5 (see usage.txt)

# Simulated Data Generation of Average Auto Theft Crimes Reported in ottawa from 2018-2023 Graph
set.seed(123)
auto_Data <- tibble(
  theft_year = sample(2018:2023, 1000, replace = TRUE)
)

# Plotting
auto_Data %>%
  ggplot(aes(x = theft_year)) + 
  labs(x = "Year", y = "Count") + 
  theme_minimal() +
  geom_histogram(stat = "count")


# Simulated Data Generation of Top 10 Car Brands Stolen from 2018-2023 Graphs
set.seed(123)
auto_Data <- tibble(
  theft_year = sample(2018:2023, 1000, replace = TRUE),
  vehicle_make = sample(c("CHEV", "DODG", "FORD", "GMC", "HOND", "HYUN", "LEXS", "MAZD", "NISS", "TOYT"), 1000, replace = TRUE)
)

# Define a function to create the plot for each year
create_brand_theft_plot <- function(year, data) {
  brand_theft <- data %>%
    filter(theft_year == year) %>%
    count(vehicle_make) %>%
    mutate(vehicle_make = recode(vehicle_make,
                                 "CHEV" = "Chevrolet",
                                 "DODG" = "Dodge",
                                 "FORD" = "Ford",
                                 "GMC" = "GMC",
                                 "HOND" = "Honda",
                                 "HYUN" = "Hyundai",
                                 "LEXS" = "Lexus",
                                 "MAZD" = "Mazda",
                                 "NISS" = "Nissan",
                                 "TOYT" = "Toyota"
    )) %>%
    arrange(desc(n)) %>%
    slice(1:10)  # Top 10 Brands
  
  ggplot(brand_theft, aes(x = vehicle_make, y = n, fill = n)) +
    geom_bar(stat = "identity") +
    theme_minimal() +
    theme(legend.position = "bottom") +
    labs(x = "Vehicle Brand", y = "Count", fill = "Count") +
    ggtitle(paste("Top 10 Brands Affected in", year))
}

# Create plots for each year
plots <- lapply(2018:2023, function(year) {
  create_brand_theft_plot(year, auto_Data)
})

# Display plots
gridExtra::grid.arrange(grobs = plots, ncol = 2)




